### ISSUE TITLE
I'm planning to switch from PPA based AppImages to the new "ArchImage" model

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/GIMP-appimage#10]
Hi everyone, I'm working on a complete switch from PPAs to Arch Linux-based AppImages using JuNest as a portable and inbuilt system.

The game is simple: install everything into a portable Arch Linux using pacman or yay, remove the unnecessary stuff and export to an AppImage.

I wrote this script to built the AppImage on your pc, I suggest to create a temporary directory to do this:

    mkdir tmp
    cd tmp
    wget https://raw.githubusercontent.com/ivan-hc/GIMP-appimage/main/gimp-junest.sh
    chmod a+x ./gimp-junest.sh
    ./gimp-junest.sh
If the mirrorlist is updated correctly (see lines 28-30) the script should build the AppImage in two minutes or less. In case of problems with mirrorlist, comment lines 28-30, JuNest will use the defaults.

And when the script has finished, just run the AppImage:

    ./*AppImage
Final size is about 250 MB (this is because I've removed a lot of stuff, if not it would be more than 500 MB).

The AppImage works great, I only need to reduce sizes.

If you are interested in improve this or have suggestions, contact me here.

If you  want to know more about ArchImages, visit https://github.com/ivan-hc/ArchImage

I'm trying to switch my PPA-based AppImages to ArchImages, being them developed by third-party developers without guarantees of continuity, and I hope my Appimages live long, also without me.

Greetings.

**Comment by dCo3lh0** [comment]
Hope your work building this AppImages work on Any Distro.

**Comment by ivan-hc** [comment]
The new ArchImage of GIMP is ready! Only 97 MB of space!

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous

For now I worked on the Stable version... so I'll switch to GIMP-DEV from AUR soon.

**Comment by ivan-hc** [comment]
Mission complete!

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous
