### ISSUE TITLE
Open files on Mounted Partitions/Drives (ArchImage Version)

### ISSUE THREAD

**Issue by dCo3lh0** [ivan-hc/GIMP-appimage#11]
I've tested both versions, both loaded well but when i try to open files on "/mnt/Projects", my folder for work space on my drive, it cant find, no mounted drives visible, if i try drag and drop files into it. It shows message error no such file or directory. Since there is no terminal output error than i cant post log here.

**Comment by ivan-hc** [comment]
This is because --bind=/mnt is not set in proot, now I'll correct it and run a GH action to build them again (extimed time 30 minutes, due to gimp-devel, built from AUR)
