### ISSUE TITLE
Some Keyboard Shorcuts not working on GIMP 2.99

### ISSUE THREAD

**Issue by dCo3lh0** [ivan-hc/GIMP-appimage#12]
I've been trying to use some shortcuts on GIMP 3 and failed (Only on GIMP 3), don't know what happened, one of them is the Increase/Decrease brush size on any tool that have changeable size, and on Interface > Change shortcuts > Tool Size the shortcut is configured there for " [ " and " ] ", but does not work. Another shortcut not working was "Ctrl +" and "Ctrl -", if i press only minus without control it zooms out but plus doesn't work with or without control.

I think this bug is related to GIMP 2.99 itself, and not yours, so i think you cant solve it, but who knows I'm a newbie onto this knowledge.

**Comment by ivan-hc** [comment]
we have only a way to discover this:

install [JuNest](https://github.com/fsquillace/junest) and then install "`gimp-devel`" using `yay` the way you do with Arch Linux normally (command `yay -S gimp-devel gzip`, YAY is preinstalled in JuNest).
