### ISSUE TITLE
Libraries included in the AppImage

### ISSUE THREAD

**Issue by rubensa** [ivan-hc/GIMP-appimage#14]
In order to be able to launch the stable **AppImage** version **2.10.34** I had to install the **libgimp2.0** and **libmypaint-1.5-1** dependency libraries.

Once installed, on launch a window is open with the following message:

> Libgimp version mismatch!
> 
> The GIMP binary cannot run with a libgimp version
> other than its own. This is GIMP 2.10.34, but the
> libgimp version is 2.10.30.
> 
> Maybe you have GIMP versions in both /usr and /usr/local ?

Should it be possible to include in the **AppImage** the exact library dependencies needed by **GIMP**?

Thanks in advance.

**Comment by rubensa** [comment]
This are the files included in **libgimp2.0** for **Ubuntu 20.04** (that should be kept -not removed- in the **AppImage**):

- /usr/lib/libgimp-2.0.so.0.1000.18
- /usr/lib/libgimpbase-2.0.so.0.1000.18
- /usr/lib/libgimpcolor-2.0.so.0.1000.18
- /usr/lib/libgimpconfig-2.0.so.0.1000.18
- /usr/lib/libgimpmath-2.0.so.0.1000.18
- /usr/lib/libgimpmodule-2.0.so.0.1000.18
- /usr/lib/libgimpthumb-2.0.so.0.1000.18
- /usr/lib/libgimpui-2.0.so.0.1000.18
- /usr/lib/libgimpwidgets-2.0.so.0.1000.18
- /usr/share/doc/libgimp2.0/changelog.Debian.gz
- /usr/share/doc/libgimp2.0/copyright

(and probably any other transitive dependency should also be kept).

The thing about an **AppImage** is that it includes everything needed (so the exact version libraries), isn't it?

**Comment by rubensa** [comment]
Just realized that I trying to use the [GIMP 2.10.34 (stable) & 2.99.16 (dev) from PPA](https://github.com/ivan-hc/GIMP-appimage/releases/tag/2.10.34-2.99.16) (as I was looking for **stable** version).

With [Continuous builds (JuNest Arch Linux-based AppImages)](https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous) it is working.

**Comment by ivan-hc** [comment]
Yes, I've stopped using the PPA version as a base due to the lack of continuity guarantees of the third-party PPA owners.

On the contrary, Arch Linux is a full distro with a big community.

I suggest you to usa AM or AppMan to keep updated the AppImage (see my best repos).

Bye

**Comment by rubensa** [comment]
As a side note, in the [README](https://github.com/ivan-hc/GIMP-appimage/blob/main/README.md) both **[AM](https://github.com/ivan-hc/GIMP-appimage/blob/main/README.md?plain=1#L20)** and **[AppMan](https://github.com/ivan-hc/GIMP-appimage/blob/main/README.md?plain=1#L21)** links reference to **AppMan** only.

**Comment by ivan-hc** [comment]
Oh my bad... thank you https://github.com/ivan-hc/GIMP-appimage/commit/d3265dce0e6c0e80a7d473cca168059d3fd04cf3
