### ISSUE TITLE
Continuous Stable builds (JuNest Arch Linux-based AppImages) does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by rubensa** [ivan-hc/GIMP-appimage#16]
Downloaded [GNU-Image-Manipulation-Program_2.10.36-3-archimage3-1-x86_64.AppImage](https://github.com/ivan-hc/GIMP-appimage/releases/download/continuous-stable/GNU-Image-Manipulation-Program_2.10.36-3-archimage3-1-x86_64.AppImage) and run but nothing happens (so I think there is some internal error in the AppImage).

Should it be possible to show the possible error messages (I saw they where redirected to /dev/null in AppRun so they are not reported back)?

If I extract the AppImage, at the end I get a "fopen error: Permission denied" (so I'm think in a symlink problem or something like so).

```bash
$ ./GNU-Image-Manipulation-Program_2.10.36-3-archimage3-1-x86_64.AppImage --appimage-extract
squashfs-root/.DirIcon
squashfs-root/.cache
squashfs-root/.cache/yay
squashfs-root/.junest
squashfs-root/.junest/bin
squashfs-root/.junest/boot
squashfs-root/.junest/dev
squashfs-root/.junest/dev/null
squashfs-root/.junest/etc
squashfs-root/.junest/etc/.pwd.lock
squashfs-root/.junest/etc/X11
squashfs-root/.junest/etc/X11/xinit
squashfs-root/.junest/etc/X11/xinit/xinitrc.d
squashfs-root/.junest/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
squashfs-root/.junest/etc/arch-release
squashfs-root/.junest/etc/audit
squashfs-root/.junest/etc/audit/audisp-remote.conf
squashfs-root/.junest/etc/audit/audit-stop.rules
squashfs-root/.junest/etc/audit/auditd.conf
squashfs-root/.junest/etc/audit/plugins.d
squashfs-root/.junest/etc/audit/plugins.d/af_unix.conf
squashfs-root/.junest/etc/audit/plugins.d/au-remote.conf
squashfs-root/.junest/etc/audit/plugins.d/audispd-zos-remote.conf
squashfs-root/.junest/etc/audit/plugins.d/syslog.conf
squashfs-root/.junest/etc/audit/rules.d
squashfs-root/.junest/etc/audit/zos-remote.conf
squashfs-root/.junest/etc/avahi
squashfs-root/.junest/etc/avahi/avahi-autoipd.action
squashfs-root/.junest/etc/avahi/avahi-daemon.conf
squashfs-root/.junest/etc/avahi/avahi-dnsconfd.action
squashfs-root/.junest/etc/avahi/hosts
squashfs-root/.junest/etc/avahi/services
squashfs-root/.junest/etc/bash.bash_logout
squashfs-root/.junest/etc/bash.bashrc
squashfs-root/.junest/etc/bindresvport.blacklist
squashfs-root/.junest/etc/binfmt.d
squashfs-root/.junest/etc/ca-certificates
squashfs-root/.junest/etc/ca-certificates/README
squashfs-root/.junest/etc/ca-certificates/extracted
squashfs-root/.junest/etc/ca-certificates/extracted/README
squashfs-root/.junest/etc/ca-certificates/extracted/ca-bundle.trust.crt
squashfs-root/.junest/etc/ca-certificates/extracted/cadir
squashfs-root/.junest/etc/ca-certificates/extracted/cadir/002c0b4f.0
...
squashfs-root/.junest/etc/kernel
squashfs-root/.junest/etc/kernel/install.d
squashfs-root/.junest/etc/keyutils
squashfs-root/.junest/etc/krb5.conf
squashfs-root/.junest/etc/ld.so.cache
squashfs-root/.junest/etc/ld.so.conf
squashfs-root/.junest/etc/ld.so.conf.d
squashfs-root/.junest/etc/ld.so.conf.d/fakechroot.conf
squashfs-root/.junest/etc/ld.so.conf.d/fakeroot.conf
squashfs-root/.junest/etc/libaudit.conf
squashfs-root/.junest/etc/libnl
squashfs-root/.junest/etc/libnl/classid
squashfs-root/.junest/etc/libnl/pktloc
squashfs-root/.junest/etc/libpaper.d
squashfs-root/.junest/etc/libva.conf
squashfs-root/.junest/etc/locale.gen
squashfs-root/.junest/etc/localtime
squashfs-root/.junest/etc/login.defs
squashfs-root/.junest/etc/machine-id
fopen error: Permission denied
```

But I can run the extracted squashfs-root/AppRun and Gimp opens.

**Comment by rubensa** [comment]
As a side note, [VLC-media-player_3.0.20-4-archimage3-x86_64.AppImage](https://github.com/ivan-hc/VLC-appimage/releases/download/continuous/VLC-media-player_3.0.20-4-archimage3-x86_64.AppImage) works without problem.

**Comment by rubensa** [comment]
Tried GNU-Image-Manipulation-Program_GIT_2.99.17.r751.05b2f93876-archimage3-2-x86_64.AppImage with same results (nothing happends on run).

Tried also extracting and run but this time no `fopen error` but the AppRun does not work.

Editing the AppRun (removing the error message redirection to /dev/null part) an running again I get:

```bash
$ squashfs-root/AppRun 
/etc/profile.d/debuginfod.sh: line 9: tr: No such file or directory
/etc/profile.d/gpm.sh: line 1: /usr/bin/tty: No such file or directory
/bin/sh: line 1: gimp-2.99: No such file or directory
```

**Comment by ivan-hc** [comment]
This is a known issue, Archimage is a container, so it uses its own $PATH.

See https://github.com/ivan-hc/AppMan/issues/25 and https://github.com/ivan-hc/AppMan/issues/26

Ubuntu is a Debian-based, so you need to change the order of $PATH in your ~/.profile file to made them work.

However, if you install them with AM or AppMan all should work fine.

Another thing, both my GIMP AppImages, my MPV and KDEgames use an AppRun a bit different from VLC, OBS and other Archimages, they contain a "`case`/`esac`" function, for example:
```
case "$1" in
	gimptool) $HERE/.local/share/junest/bin/junest -n 2> /dev/null -- gimptool "$@";;
	*) $HERE/.local/share/junest/bin/junest -n 2> /dev/null -- gimp "$@";;
esac
```
To select both `gimptool` and `gimp` in the internal /usr/bin

If you want to build the AppImage in place, you need to change the AppRun in the script, try to replace the function above with this:
```
$HERE/.local/share/junest/bin/junest -n 2> /dev/null -- gimp "$@"
```

Also this is a know issue https://github.com/ivan-hc/MPV-appimage/issues/12

NOTE: the Archimages now all work without `proot` but with `namespaces`, learn more at https://github.com/fsquillace/junest
