### ISSUE TITLE
Gimp version 2.10.36 for Ubuntu 22 LTS

### ISSUE THREAD

**Issue by in4matix** [ivan-hc/GIMP-appimage#18]
Hi. Thank you for making these Appimages of Gimp available. Could you make a Gimp version 2.10.36 for Ubuntu 22 LTS available please?

**Comment by ivan-hc** [comment]
Hi, is the JuNest-based one not working for you?

If for some reasons you need the one based on Debian/Ubuntu, follow the instructions here:

https://github.com/ivan-hc/GIMP-appimage?tab=readme-ov-file#5-ppa-based-appimages

**Comment by in4matix** [comment]
I found this one, "GNU-Image-Manipulation-Program_2.10.36-1-x86_64.AppImage", in my backups, seems to be working fine, thanks.
