### ISSUE TITLE
WPS Office

### ISSUE THREAD

**Issue by in4matix** [ivan-hc/GIMP-appimage#19]
Tried to make an Appimage, but no luck. I think too many missing dependencies. You ever try?

**Comment by ivan-hc** [comment]
Please, reopen the issue at https://github.com/ivan-hc/ArchImage

**Comment by ivan-hc** [comment]
@in4matix 

PS: you may be interested in this https://github.com/ivan-hc/WPS-Office-appimage it is based on the official .deb package
