### ISSUE TITLE
bwrap error

### ISSUE THREAD

**Issue by shlozm** [ivan-hc/GIMP-appimage#20]
I installed gimp locally using appman, when I try to launch from terminal I get the following error:
bwrap: Can't find source path /opt: No such file or directory
Bubblewrap is installed.
Please help

**Comment by ivan-hc** [comment]
it seems that you have not an /opt directory on your system
```
sudo mkdir /opt
```

**Comment by shlozm** [comment]
Thanks that worked. I should have checked.
