### ISSUE TITLE
Anche su EndavourOS Gimp-develop-git non compila... se le appimage di 2..99.19 non riescono non è colpa tua.

### ISSUE THREAD

**Issue by vitforlinux-gimp** [ivan-hc/GIMP-appimage#22]
Io consiglio pazienza e un bel cono gelato.
Ciao Vit

**Comment by ivan-hc** [comment]
Si, lo so, è un nuovo modulo relativo a Meson che hanno inserito. Infatti ho contattato il manutentore del PKGBUILD per segnalargli il problema https://github.com/bartoszek/AUR-gimp-git/issues/10
