### ISSUE TITLE
I don't understand how to open JuNest AppImages

### ISSUE THREAD

**Issue by yataghan012** [ivan-hc/GIMP-appimage#26]
Hi, I downloaded "GNU-Image-Manipulation-Program_2.10.38-1-archimage3.4.1-1-x86_64.AppImage" and "GNU-Image-Manipulation-Program_DEV_2.99.18-2-archimage3.4-x86_64.AppImage", and can't open them.

I installed JuNest from both the pamac (junest-git) and manually (https://github.com/fsquillace/junest). I tried opening the images from the host distro and nothing shows up (execv error: No such file or directory), I also tried from the JuNest environment located at /home/manjaro/.junest/ and says "cannot execute: required file not found". I've made the images executables through chmod.

I'm on Manjaro, Linux LTS 6.6.32-1.

**Comment by ivan-hc** [comment]
Hi, why you should use JuNest to run these Appimages? They are normal Appimages (built using JuNest), its enough to made them executable and run them


https://github.com/ivan-hc/GIMP-appimage/assets/88724353/85145cae-5653-48fc-b5eb-6867f2e67e78

**Comment by yataghan012** [comment]
At first I tried not using Junest, but it doesn't work either way.
says "execv error: No such file or directory"

The PPA Appimages do work, though.

**Comment by ivan-hc** [comment]
I need to see a video, some screenshots or at least a log, I can't figure out what happens without enough information

**Comment by yataghan012** [comment]
![Captura de pantalla_2024-06-03_21-36-42](https://github.com/ivan-hc/GIMP-appimage/assets/96704686/0c5576c6-cf69-4a64-8895-7854b449bc3f)

**Comment by ivan-hc** [comment]
This issue remembers me this https://github.com/ivan-hc/AM/issues/107

Would you like to try using "AM" or AppMan instead?

https://github.com/ivan-hc/AM

https://github.com/ivan-hc/AppMan

**Comment by yataghan012** [comment]
> This issue remembers me this [ivan-hc/AM#107](https://github.com/ivan-hc/AM/issues/107)
> 
> Would you like to try using "AM" or AppMan instead?
> 
> https://github.com/ivan-hc/AM
> 
> https://github.com/ivan-hc/AppMan

How can use AM or AppMan to open AppImages double clicking it?

**Comment by ivan-hc** [comment]
The ways you can use my gimp appimages using AM or AppMan:

- use `am -i gimp` or `appman -i gimp` to install it as any other normal package manager (not a portable way), see https://github.com/ivan-hc/AM#how-to-list-installed-applications
- use `am --launcher '/path/to/appimage'` or `appman --launcher '/path/to/appimage'` to create a launcher in your apps menu and to give it a name to launche from the terminal, see https://github.com/ivan-hc/AM#how-to-create-launchers-and-shortcuts-for-my-local-appimages

**Comment by ivan-hc** [comment]
Anyway, it's strange that AppimageLauncher can't launch my GIMP AppImages. You should contact the author of AppimageLauncher to report the problem.

Have you tried launching any other AppImage I created? The list is here https://github.com/ivan-hc#my-appimage-packages

**Comment by ivan-hc** [comment]
Also, I've seen that AppimageLauncher is a Type2 AppImage

![Istantanea_2024-06-05_01-44-15](https://github.com/ivan-hc/GIMP-appimage/assets/88724353/894bb639-2c80-4594-9db0-08392f7ced87)

it means that it requires libfuse2 to work... while all my AppImages are Type3. I don't know how it manages Type3 AppImages. I only know that Arch Linux and its derivatives have `fusermount` included in the package `fuse2` while Type3 AppImages require `fusermount` as a symlink to `fusermount3` to work.

I've already faced this issue two times https://github.com/ivan-hc/AM/discussions/387 https://github.com/ivan-hc/Chrome-appimage/issues/3

I don't know if this is your case.

**Comment by yataghan012** [comment]
> The ways you can use my gimp appimages using AM or AppMan:
> 
>     * use `am -i gimp` or `appman -i gimp` to install it as any other normal package manager (not a portable way), see https://github.com/ivan-hc/AM#how-to-install-applications
> 
>     * use `am --launcher '/path/to/appimage'` or `appman --launcher '/path/to/appimage'` to create a launcher in your apps menu and to give it a name to launche from the terminal, see https://github.com/ivan-hc/AM#how-to-create-launchers-and-shortcuts-for-my-local-appimages

It doesn't launch with AM, same error.

**Comment by yataghan012** [comment]
> Also, I've seen that AppimageLauncher is a Type2 AppImage
> 
> ![Istantanea_2024-06-05_01-44-15](https://private-user-images.githubusercontent.com/88724353/336638732-894bb639-2c80-4594-9db0-08392f7ced87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDczNjEsIm5iZiI6MTcxNzU0NzA2MSwicGF0aCI6Ii84ODcyNDM1My8zMzY2Mzg3MzItODk0YmI2MzktMmM4MC00NTk0LTlkYjAtMDgzOTJmN2NlZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAwMjQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDg5ZTczZDgwMzRkYzFhNjZjN2JkNTE3N2ZlZGNmMzVhNWMwZmQzOGIyNmNlOWY0YTE1Mjg2NDQ4MDczMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ChXkHAIL6OMYIrWLbil2rk7rOQ_Wut1R1O4075LtmE)
> 
> it means that it requires libfuse2 to work... while all my AppImages are Type3. I don't know how it manages Type3 AppImages. I only know that Arch Linux and its derivatives have `fusermount` included in the package `fuse2` while Type3 AppImages require `fusermount` as a symlink to `fusermount3` to work.
> 
> I've already faced this issue two times [ivan-hc/AM#387](https://github.com/ivan-hc/AM/discussions/387) [ivan-hc/Chrome-appimage#3](https://github.com/ivan-hc/Chrome-appimage/issues/3)
> 
> I don't know if this is your case.

I don't think it's a AppimageLauncher problem.

**Comment by ivan-hc** [comment]
my PPA ones are type2, I don't update them from before I switced to type3

can you try other ones from my lists? For example, google-chrome, edge... the ones marked as based on .deb

There are also the ones marked as "JuNest, Arch Linux (ArchImage)", for example VLC or OBS Studio... try also them and see if they work with AppimageLauncer, just for tests.

**Comment by yataghan012** [comment]
VLC , chrome, edge and OBS studio don't work, same error.

What does "Archimage / JuNest require /run/user to work" do i need to configure something?

**Comment by ivan-hc** [comment]
Chrome and Edge are based on the official .deb packages, the others are Archimages.

That fix was done after an experiment I did for non-systemd users. In brief, Archimage is an arch Linux container (see [JuNest](https://github.com/fsquillace/junest)) into an AppImage (see [Archimage](https://github.com/ivan-hc/ArchImage)). It uses its internal "bubblewrap" to integrate itself on the host system. To do so, it needs to see some directories on the system, nd the two that must do present are /home and /run/user... all others are optional so I've changed this in the last commit. However, non-systemd users need at least to create an empty directory named /run/user on their system. You use anjaro, so you use systemd like many others.

However, let talk about your issue... all my Type3 AppImages are not working with AppImageLaincher... while the Type3 ones are working... I'd like to see other Type3 not developed by me to see if your is an issue with these... I need someone that suggests me.

@Samueru-sama , sorry if I always call you, but I don't know other AppImage packager experts other than you.

In brief, @yataghan012 uses Manjaro and none of my AppImages is working on AppimageLauncher. Any idea?

**Comment by Samueru-sama** [comment]
appimagelauncher is broken, this is why I usually have this message on my appimages: 

```
It is possible that this appimage may fail to work with appimagelauncher, I recommend this alternative instead: https://github.com/ivan-hc/AM
```

When I made the script that made the Ryujinx appimage: https://github.com/Ryujinx/Ryujinx/issues/2492

The user there could not even open `Go appimagetool` to make the appimage because of appimagelauncher.

I consider appimagelauncher dead at this point, it's last stable release was in 2020 while its last pre-release was in 2022.

**Comment by yataghan012** [comment]
> appimagelauncher is broken, this is why I usually have this message on my appimages:
> 
> ```
> It is possible that this appimage may fail to work with appimagelauncher, I recommend this alternative instead: https://github.com/ivan-hc/AM
> ```
> 
> Back when yuzu was still around, it also failed to integrate its appimage.
> 
> When I made the script that made the Ryujinx appimage: [Ryujinx/Ryujinx#2492](https://github.com/Ryujinx/Ryujinx/issues/2492)
> 
> The user there could not even open `Go appimagetool` to make the appimage because of appimagelauncher.
> 
> I consider appimagelauncher dead at this point, it's last stable release was in 2020 while its last pre-release was in 2022.
> 
> Also @ivan-hc I am on a non systemd distro and I have a `/run/user` directory.

Is there another way to launch AppImages by double clicking them and in a portable way?

**Comment by ivan-hc** [comment]
you should completelly remove appimagelauncher, see https://github.com/ivan-hc/AM/issues/107

**Comment by Samueru-sama** [comment]
Yeah as Ivan said, you have to remove appimagelauncher and **reboot**. I don't know why this happens but it was something that I also replicated back then.

**Comment by yataghan012** [comment]
I rebooted an my AM launcher finally works, am I supposed to make a launcher for each AppImage i have an launch them from the terminal from now on?

**Comment by Samueru-sama** [comment]
> I rebooted and my AM launcher finally works, am I supposed to make a launcher for each AppImage i have and launch them from the terminal from now on?

You can also just use am to install them and it puts them in PATH automatically. 

`am -i gimp` for example will install the gimp appimage.

**Comment by yataghan012** [comment]
Nevermind, it works double clicking it too.

**Comment by yataghan012** [comment]
Nevermind, it works double clicking it too. Thanks I will keep using AM.
