### ISSUE TITLE
Su Mint 22 Beta e FunOS (Ubuntu 24.04)  "bwrap: setting up uid map: Permission denied"

### ISSUE THREAD

**Issue by vitforlinux-gimp** [ivan-hc/GIMP-appimage#27]
errore completo è questo:
`/GNU-Image-Manipulation-Program_GIT_2.99.19.r784.389b6d98b4-1-archimage3.4.1-1-x86_64-a5f2f1b02feebbdb8af69205166aeab0.AppImage 
bwrap: setting up uid map: Permission denied
Error: Something went wrong while executing bwrap command. Exiting`

Ma su Debian 12 e Arch (dove ci sono sia fuse2 che fuse3) tutto funziona.... Viva Debian e Arch!

Le appimage 2.99.16 funzionano, ma non è il caso di usarle: non caricano gli script-fu... come il 2.99.18 originale in deb da PPA su Ubuntu.

Installare fuse 2 non risolve.

Ma ora basta, non ci pensare, fa troppo caldo.
Ciao Vit

**Comment by ivan-hc** [comment]
> Ma ora basta, non ci pensare, fa troppo caldo. Ciao Vit

ahahaha

Almeno con qualcuno posso rispondere in italiano, grazie

Parlando di inglesismi, "googlando" un pò ho notato che il problema embra essere legato ad Apparmor https://www.google.com/search?client=firefox-b-d&q=bwrap%3A+setting+up+uid+map%3A+Permission+denied+Error

Ricordo che un utente di [AM](https://github.com/ivan-hc/AM) ebbe lo stesso problema https://github.com/ivan-hc/AM/issues/654

Sembra che Canonical cerchi in tutti i modi di farsi schifare https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces

In breve, leggi il grassetto in fondo a questo paragrafo https://github.com/ivan-hc/AM?tab=readme-ov-file#cannot-mount-and-run-appimages prima dei pulsanti.

**Comment by vitforlinux-gimp** [comment]
Ho fatto due prove, ed è proprio Apparmor a causare "il problema" se lo si disinstalla e si riavvia la appimage Poi funziona.

Un altro programma da non usare è appimage launcher... anche lui è un ostacolo, più che un aiuto, se si usa una distro a base Ubuntu 24.04.

Se non ti fosse scappato un commento in italiano ora ti starei scivendo in Goog-matic-glese, perciò il primo che devi ringraziare sei testesso.

Dimenticavo, se ti piace giocare con gli script-fu ci sono quelli che ho aggiornato [Download](https://github.com/vitforlinux-gimp/scm/releases)
Ciao!

**Comment by ivan-hc** [comment]
Ti ringrazio, ma non uso gimp per chissà cosa, è meglio di `converseen` per quanto riguarda la conversione di singoli file .ico e .svg in .png, quando devo creare le icone per il mio sito https://portable-linux-apps.github.io

Questa AppImage l'ho creata più per arricchire il mio database per il package manager "AM", visto che l'unica disponibile era ferma alla versione 2.10.25, e volevo fornire qualcosa di più aggiornato possibile, altrimenti il mio sarebbe stato un qualsiasi gestore di pacchetti AppImage, come ce ne sono già. Volevo fare qualcosa di meglio. E il vostro interesse per questa AppImage mi da ragione.

Per citare Lino Banfi "la sua soddisfazione è il nostro maggior premio"  https://www.youtube.com/watch?v=P9RhdL5fzqE

**Comment by vitforlinux-gimp** [comment]
Volevo solo farti un regaluccio...

Forse ti può far piacere avere [Bimp](https://vitforlinux.wordpress.com/2023/11/05/avere-il-plugin-bimp-per-gimp-su-debian-e-altre-distro-gnu-linux-senza-compilarlo/)  ricavandolo da un pacchetto di Arch, ma a te compilare non spaventa.

Il tuo Gimp in appimage è prestigioso, e il tuo sforzo utilissimo... non il vecchio 2.10.22 di Debian, e poi il tuo python2 fa qualcosa in più di quello nuovo di Arch. Insomma la botte piena e la moglie ubriaca.

Però a un certo punto devo smetterla di ringraziare... sempre per il caldo. 
Ciao!

**Comment by ivan-hc** [comment]
> Volevo solo farti un regaluccio...

gia mi hai fatto un bel regalo usando la mia AppImage e parlandone nel tuo blog:
- https://vitforlinux.wordpress.com/2024/04/11/e-arrivato-gimp-2-99-19-in-appimage-per-provarlo-senza-sapere-come-si-compila-e-senza-avere-aur-ne-archlinux-grazie-a-ivanhc/
- https://vitforlinux.wordpress.com/2024/04/15/gimp-2-10-36-con-python2-in-appimage-grazie-ancora-ivan-hc/

...quindi grazie Vit! :)

**Comment by vitforlinux-gimp** [comment]
Pensa che del mio blog cerco di tenere il segreto... ma qualcuno lo scopre sempre , ho paura di diventare l'Aranzulla di Linux :-)
Ciao!

**Comment by ivan-hc** [comment]
> Pensa che del mio blog cerco di tenere il segreto... ma qualcuno lo scopre sempre , ho paura di diventare l'Aranzulla di Linux :-) Ciao!

Fidati che non ci vuole molto a diventare Aranzulla, visto che le sue guide non risolvono mai i miei problemi tecnologici.
