### ISSUE TITLE
Latest GIT Release 2.99.19.r1124-cb796c57d6 broke, after starting.

### ISSUE THREAD

**Issue by dCo3lh0** [ivan-hc/GIMP-appimage#29]
after loading the AppImage, it reaches that welcome screen with file selection just after, on that screen it crashes. So, it starts, but crashes just after launching the main window.

**Comment by ivan-hc** [comment]
This may happen because there are already old configuration files.

Create a .home directory near the Appimage using the command
```
./*AppImage --appimage-portable-home
```
if you use "AM", use the command
```
am -H gimp-git
```
same for AppMan
```
appman -H gimp-git
```
and then launch the app again.

I've just installed and tested it and I can't reproduce the issue.

**Comment by dCo3lh0** [comment]
yeah maybe its some misconfiguration in some file that's causing this in default folders, i've used this --appimage-portable-home option and it created the directory in same folder and it started completely fine now.

**Comment by ivan-hc** [comment]
gimp-git is still a development release, so new configurations may always be broken due to the old ones, and this made the app crashing.

If you face the same problem, please re-open this issue.
