### ISSUE TITLE
Update GIMP Developer Edition to 2.99.12

### ISSUE THREAD

**Issue by TotalCaesar659** [ivan-hc/GIMP-appimage#3]
Hi, could you update GIMP Developer Edition in [releases](https://github.com/ivan-hc/GIMP-AppImage/releases) to 2.99.12? There are many [enhancements](https://www.gimp.org/news/2022/08/27/gimp-2-99-12-released/).

**Comment by ivan-hc** [comment]
Hi, it seems to be available only the v2.99.10 on the PPA from where this AppImage is created

https://launchpad.net/~mati75/+archive/ubuntu/gimp30

I can provide only that version, however it may be helpful if someone helps me in providing a github action to maintain this repository alive, sadly I have not much time latelly. 
If you need a more recent version, you can install it using [AM](https://github.com/ivan-hc/AM-Application-Manager) (with sudo) or [AppMan](https://github.com/ivan-hc/AppMan) (without sudo), the last one has also an option to switch the main folder of the apps from ~/.opt to another one you choose.

**Comment by TotalCaesar659** [comment]
Ah, you don't compile from sources and get them from PPA? OK. I've used builds from this [repo](https://github.com/aferrero2707/gimp-appimage) before, but it is outdated for a long time, so I've found your one.
Thanks for clarification, I just wanted to see what's new in dev builds.

**Comment by ivan-hc** [comment]
Created a GitHub action to compile and redistribute both Stable and Development edition you can download from the link below

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous

The release is updated each Sunday
