### ISSUE TITLE
Come avrai visto da qualche giorno gimp-git non compila... 

### ISSUE THREAD

**Issue by vitforlinux-gimp** [ivan-hc/GIMP-appimage#30]
Ho provato sulla EndavourOS, e niente... allora mi sono ricordato che "da giovane" usavo il repo **ArchlinuxCN** (dalla Cina), ieri ho provato il loro gimp-git precompilato (che evidentemente non usa il PKGBUILD di AUR) e oggi l'ho aggiornato e si è aggiornato.

Non è compatibile con Gimp 2.10 perché installa oltre a gimp-git anche babl-git e gegl-git, ma che importa? C'è Gimp 2.10.38 in Appimage.

Grazie e CIAO!

**Comment by ivan-hc** [comment]
Ciao, ho sentito parlare dell repository cinese, ma come si attiva?

Ho visto che hanno molti più programmi, forse più di ChaoticAUR, ma non sono sicuro.

Se hai più fonti dalle quali posso attingere, oltre al wiki di Arch Linux, te ne sarei grato.

**Comment by vitforlinux-gimp** [comment]
Ho preso le informazioni dal wiki... e un po' ci ho messo le mani, perché prima di aggiungere la firma bisogna attivarlo senza e quindi aggiungere a /etc/pacman.conf:
`[archlinuxcn]
SigLevel = Never
Server = http://repo.archlinuxcn.org/$arch` 
poi sudo pacman -Syy
Hanno il repo su Github:[https://github.com/archlinuxcn/repo/tree/master/archlinuxcn](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn)
puoi vedere all'interno di ogni cartella il [PKGBUILD](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/gimp-git) qui quello di Gimp-git... che da molta ispirazione, dato che il pacchetto c'è.

Ah, dimeticavo... ho messo l'indirizzo del repo... per far vedere il numero sterminato ti pacchetti,e le cartelle contenenti il PKGBUILD, ma è meglio linkare anche la pagina iniziale con le istruzioni:[https://github.com/archlinuxcn/repo](https://github.com/archlinuxcn/repo).

Ora succederà la catastrofe... tutti i pacchetti di ArchLinuxCN diventeranno AppImage... no, non tutti, alcuni non ha senso.

Ciao!!!

**Comment by ivan-hc** [comment]
grazie, ma no, non ci tengo ad aprire altri repository, ho già più di 70 appimage e altri progetti relativi ad essi. Un pò troppi da mantenere da solo, capiscimi.

**Comment by vitforlinux-gimp** [comment]
Per quello dicevo catastrofe... io non so quanti sono a curare archlinuxcn, in Italia trovare qualche università che appoggi un repo simile è improbabile, ma magari in Cina si.

P.S. ho provato a compilare gimp-git dal PKGBUILD di archlinuxcn e sono arrivato alla fine, ma come previsto mi ha tolto gimp 2.10.

**Comment by ivan-hc** [comment]
A mio parere, i cinesi ne fanno di cose grandiose, e poi statisticamente sono quasi settimo della popolazione della terra, di sicuro menti brillanti e manodopera non mancano a loro.

D'altronde, se due pacchetti, da due repository diversi, hanno lo stesso nome, è normale che entrino in conflitto.

Per quanto riguarda gimp-git su AUR, ormai ci ho fatto l'abitudine, ed essendo un workflow giornaliero nel mio repo, ricevere una notifica di fallimento ogni sera mi fa sentire meno solo xD

**Comment by vitforlinux-gimp** [comment]
Il pacchetto gimp-git di AUR non rimuove gimp 2.10, quello di ArchLinuxCN si, in certi momenti di febbre (quando mi viene penso pazzie) penso a provare se Gimp 2.10 cammina con gegl-git e babl-git... poi la temperatura si abbassa e torno saggio.

Comuque ora ho 2.99.19 di ArchLinuxCN e 2.10 hybrid in AppImage... e ho la moglie piena e la botte ubriaca... o era il contrario?

E poi dicono dei distro hopper, ma non si può fare altro che cambiare ogni tanto.
Ciao!

**Comment by vitforlinux-gimp** [comment]
... Tanto per essere fastidioso: su ARTIX ho modificato il PKGBUILD di gimp-git facendo un incrocio di quello di ArchlinuxCN e di gimp-develop-git, e ora ho sia 2.10 (super-accessoriato, gli manca solo gmic) che 2.99.

Ora il problema che ho è capire come metterlo su AUR,  così da fartelo usare in automatico... magari un altro giorno.
Ciao!

**Comment by ivan-hc** [comment]
Grazie, non ti preoccupare, al limite potrei cercare un nuovo metodo per compilare gimp da zero, avevo intenzione di mettere in pratica alcuni nuovi metodi poichè alcuni Archimage che avevo già da prima, non stanno funzionando come dovrebbero.

Per il momento sono molto impegnato a migliorare "AM", il mio gestore pacchetti. Ma prometto che come mi libero un attimo, cerco di lavorare a GIMP.

**Comment by vitforlinux-gimp** [comment]
Non lavorare a Gimp, basta usare i PKGBUILD di archlinuxCN (a ma CN fa ridere per via di Cuneo... e Totò).
Comunque il mio PKGBUILD pasticciato funziona, ma ha un numero di versione bizzarro 2:(un numerone esadecimale) che non è elegante.
Gimp 2.10 funziona con Gegl-git e Babl-git.
Il problema è che tutto mi funziona, ma sempre mi impiccio in una cosetta come il numero di versione... e li rimango piantato, un pasticcio così non lo posso rendere pubblico.

**Comment by vitforlinux-gimp** [comment]
Se prendi il PKGBUILD  e il linux.gpl (è un gradiente) dal repo archlinuxCN poi con makepkg -si si compila e si installa, a questo punto potresti fare un AppImage con il numero di versione strano (però aggiornatissimo)... come il mio pacchetto.
Considera che il manutentore del pacchetto è un ucraino che abita sul confine polacco... credo che non sempre abbia tempo.

**Comment by ivan-hc** [comment]
Ciao caro, ho appena finito di testare e caricare lo script per la costruzione di GIMP GIT da repo.archlinuxcn.org come da te suggerito, e sembra funzionare bene. Risulta anche più piccolo, 170 MB contro gli attuali 240.

Avvierò il flusso di lavoro proprio ora, che impiega 2-3 minuti sul mio PC.

PS: scusa se non ti ho risposto più, avevo molto da fare con "AM"/"AppMan" negli ultimi giorni. Ciao, e grazie dei consigli!

**Comment by vitforlinux-gimp** [comment]
![ottimo](https://github.com/user-attachments/assets/e2d1f93b-d15d-4877-b54c-6775397e35a9)

Devo dire che anche a me sembra meglio, più bello e più veloce, credo per via di gegl-git e babl-git.

Ho provato su Mint e MX Linux con soddisfazione, invece su antiX fa un capriccetto, che si risolve estraendo l'appimage:
`bwrap: Can't create file at /etc/asound.conf: Read-only file system`
Ma ve bene così.
Il mio giornalista preferito Paolo Attivissimo parlava di AI che consuma troppo, ora usando il pacchetto cinese se ne risparmia un po'... oltre al tempo. 

Ciao e molti ringraziamenti.

**Comment by ivan-hc** [comment]
da https://vitforlinux.wordpress.com/2024/08/22/gimp-2-99-19-nuove-complicazioni/

> Il problema ora è: dirlo o non dirlo a IvanHC? Alla fine l’ho detto.

troppo tardi, ti leggo di tanto in tanto, anche se non sono un malato di GIMP (lo uso solo per ridimensionare/convertire immagini, o piccoli ritocchi/disegni).

Per quanto riguarda il problema di /etc/asound.conf, il problema è `--ro-bind-try /etc/asound.conf /etc/asound.conf \`, presente nel nuovo script. Essendo `--ro-bind-try` probabilmente pretende che un file `/etc/asound.conf` esista sul sistema, e se non ricodo male antiX è una distro molto minimale, e se non erro non aveva SystemD (l'ho usata una volta per un video in cui facevo una MatriosKa di distribuzioni con VirtualBox installato in un altro VirtualBox, su un sistema con appena 5 GB di RAM, altri tempi).

**Comment by vitforlinux-gimp** [comment]
/etc/asound.conf in antiX c'è, però non c'è nell'Appimage.(forse basta metterlo... rimane vuoto)
Funziona se con AM uso la sandbox, ma non funziona se non la uso... bizzarro!

Per quanto riguarda il mio sito non ti sentire obbligato a guardarlo... serve più che altro a sfogarmi, ho da tempo in testa un post dal titolo: "L'informatica è nelle case da 25 anni... c'era tempo per 5 lauree, e ancora non la si sa usare", ma è solo un progetto.

Comunque approfitto che sei italiano come me... e per fraintenderci non dobbiamo passare attraverso l'inglese :-D

Io sono più vecchio... ho fatto grafica con 80MB di Ram (P1 100)e Virtualbox con 2GB e P4 3000 (Hypertreading).
Ciao!

**Comment by ivan-hc** [comment]
eh, beh... il mio primo OS è stato Windows 98, ho 38 anni

**Comment by vitforlinux-gimp** [comment]
Fammi contare... ho 52 anni, ho cominciato con Sharp e ZX Sinclair... non li avessi mai usati non metterei le mani nei file, credo che a un  certo punto nessuno avrà più iniziativa, aspettano tutti che "qualcuno" faccia le cose, ma sono loro quel qualcuno, con Android il copia e incolla sta andando fuori moda.
Dai basta sembra Facebook!

**Comment by ivan-hc** [comment]
OK, ciao Vit, e grazie del suggerimento su gimp-git

**Comment by vitforlinux-gimp** [comment]
Scusa, oggi mi hanno fatto arrabbiare: mi hanno chiesto come si usa WeTransfer... stando lontano dal computer, è una cosa che mi rende furioso.
Ciao e a presto... con il prossimo difettuccio.

**Comment by vitforlinux-gimp** [comment]
Ora la Appimage gimp-git funziona ottimamente anche su antiX... malgrado sia una distro strana.
Ringrazio molto (come direbbe Charlie Chan).

**Comment by ivan-hc** [comment]
> Ora la Appimage gimp-git funziona ottimamente anche su antiX... malgrado sia una distro strana.

si, ho aggiunto un fix su questo e gli altri Archimage che ho costruito https://github.com/ivan-hc/GIMP-appimage/commit/b90182bbf1eadde6df07b4e0b77425388271da39 , grazie per avermi indirizzato all'errore.

> Ringrazio molto (come direbbe Charlie Chan).

o google traduttore su una pagina giapponese/cinese xD (Google è sempre più in declino).

**Comment by vitforlinux-gimp** [comment]
Gli errori sono una cosa misteriosa... non vengono uguali a tutti, e chi li ha fa bene a condividerli.

Charlie Chan è un cinese, ma fa l'ispettore di polizia a Honolulu... in vecchi film anni '40, in uno sale perfino sul dirigibile Hindenburg, non saprò mai se è quello vero.
Finchè c'è Android ci sarà Google... per fortuna, se no solo Apple.

**Comment by vitforlinux-gimp** [comment]
Nuovo problema, ma tu non puoi farci niente GRUNT!!! 
Gli script-fu SCM non caricano, ho provato una versione normale, più nuova compilata e fa lo stesso errore.
Ma perché non ho fatto il pizzaiolo? Tu sei ancora in tempo, vai a fare un corso di arte bianca... così hai un'alternativa.
Ciao.

**Comment by vitforlinux-gimp** [comment]
Release 53025.6f8231eee62 Nuovamente funzionante.
Ciao!

**Comment by vitforlinux-gimp** [comment]
A quanto pare il gimp-git da ArchLinuxCN continua a funzionare, mentre Gimp-develop-git ha avuto bisogno di cure per compilarsi... me la suono  e me la canto!

Sei su https://www.alternativalinux.it/il-formato-appimage-di-software-per-linux/
e io non c'entro affatto!

**Comment by vitforlinux-gimp** [comment]
![Buonissimo NATALE](https://github.com/user-attachments/assets/3018aa75-7e12-427a-ac9e-05371b53293d)

Molti molti auguri di Buonissimo NATALE!!!

**Comment by ivan-hc** [comment]
Auguri anche a te Vit, un abbraccio
