### ISSUE TITLE
Presto uscirà Gimp 3, ma ti invito a tenere il tuo fantastico Gimp 2.10 hybrid... molti lo apprezzano.

### ISSUE THREAD

**Issue by vitforlinux-gimp** [ivan-hc/GIMP-appimage#32]
Continuo a stare dietro a Gimp-git, quasi tutti i giorni e il giorno in cui Gimp 3 sarà lo standard è quasi arrivato.

Proprio ieri in Gimp 3.0rc1 (noto ancora come 2.99.19) sono spariti un po' di collegamenti a plugin GEGL, quindi alcune cose non si possono fare più via script-fu scm... forse in un futuro le cose saranno ripristinate. Avrei tanto voluto che le togliessero prima... così da non mettermi troppi grilli per la testa.

Nel frattempo c'è solo Gimp 2.10 che funziona completamente, e in alcuni casi l'Appimage di Gimp 2.10 Hybrid ha risolto problemi anche con i vecchi script in python 2, che al momento non hanno sostituti. Ci sono alcuni script che per funzionare hanno bisogno di un python2 poco recente.

Mi è capitato di parlare bene di te su Gimp-forum, pensa la tua appimage di Gimp 2.99.19 funziona meglio di quella "autentica" dei developer di Gimp, sembra incredibile.

Perciò la richiesta: tieni le Appimage di Gimp 2.10, saranno utili ai grafici linuxiani ancora per parecchio tempo. 

Ciao.

**Comment by ivan-hc** [comment]
Grazie Vit, vorrà dire che disabiliterò il flusso di lavoro github per GIMP Hybrid. Non ero sicuro che funzionasse, visto lo scarso numero di feedback... ma tu mi hai confermato che funziona. Grazie!

**Comment by vitforlinux-gimp** [comment]
Purtroppo su Github non c'è altro che le issues, ma se uno volesse dire grazie è più difficile... forse doverbbe essere un po' più social, ma allora ci sarebbero i troll e sarebbe necessario tenerli d'occhio.

Grazie ancora e Ciao.

**Comment by vitforlinux-gimp** [comment]
Non sono troppo da social, il problema che mi faccio è che se si scrive qualcosa rimane, e poi quando le cose cambiano si è a disagio, pensa al politically correct, che solo pochi anni fa non c'era.

In questi giorni ho cancellato da un mio vecchio blog un post spiritoso sull'influenza suina, che ora mi imbarazzava.

Comunque nessuno mi vieta di scrivere una issue e dilagare, poi tu dopo averla letta la cancelli... e altrettanto a te, ho un programma  [yudo](https://github.com/vitforlinux-gimp/yudo), che non è per niente interessante... se ci fai una issue io la leggo.
