### ISSUE TITLE
Appimage from Continuous git branch won't run - bwrap issue

### ISSUE THREAD

**Issue by SebastianMpl** [ivan-hc/GIMP-appimage#33]
Hi,

Running Appimage file from Continuous git branch shows this:

```
~/Pobrane> ./GNU-Image-Manipulation-Program_GIT_53509.817e19ee38c-1-archimage3.4.4-2-x86_64.AppImage
bwrap: Can't find source path /etc/localtime: Not a directory

```
and quits.

Stable build works fine.

Could you please check it?

Thank you

**Comment by ivan-hc** [comment]
Hi, what is your distro?

This AppImage is an Arch Linux container into an AppImage, it uses its own Bubblewrap (command `bwrap`) to mount some mountpoints on the host.

In your case, it is looking for a file named `/etc/localtime`.

It would be enough to create an empty one if you have not one on your system.

If you extract the AppImage
```
./*.AppImage --appimage-extract
```
...in the extracted squashfs-root directory you will see the AppRun script, the core script of every AppImage, and this is the content of the mine
```
	#!/bin/sh
	HERE="$(dirname "$(readlink -f $0)")"
	export UNION_PRELOAD=$HERE
	export JUNEST_HOME=$HERE/.junest
	export PATH=$PATH:$HERE/.local/share/junest/bin

	BINDS=" --dev-bind /dev /dev \
		--ro-bind /sys /sys \
		--bind-try /tmp /tmp \
		--proc /proc \
		--ro-bind-try /etc/resolv.conf /etc/resolv.conf \
		--ro-bind-try /etc/hosts /etc/hosts \
		--ro-bind-try /etc/nsswitch.conf /etc/nsswitch.conf \
		--ro-bind-try /etc/passwd /etc/passwd \
		--ro-bind-try /etc/group /etc/group \
		--ro-bind-try /etc/machine-id /etc/machine-id \
		--ro-bind-try /etc/asound.conf /etc/asound.conf \
		--ro-bind-try /etc/localtime /etc/localtime \
		--bind-try /media /media \
		--bind-try /mnt /mnt \
		--bind-try /opt /opt \
		--bind-try /usr/lib/locale /usr/lib/locale \
		--bind-try /usr/share/fonts /usr/share/fonts \
		--bind-try /usr/share/themes /usr/share/themes \
		--bind-try /var /var \
		"

	EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
	case "$1" in
		gimptool) $HERE/.local/share/junest/bin/junest -n -b "$BINDS" -- $(echo $EXEC | sed s/-/tool-/g) "$@";;
		*) $HERE/.local/share/junest/bin/junest -n -b "$BINDS" -- $EXEC "$@";;
	esac
```
well, the line responsible of that error is this
```
		--ro-bind-try /etc/localtime /etc/localtime \
```
...this is the disadvantage of using containers into AppImages. they already have their isolation system, so to work with an host system, they require that some files are present. Errors like these happen normally on non-systemd distros.

**Comment by SebastianMpl** [comment]
Thank you for your explanation. I have archbang and /etc/localtime was a symlink somewhere. After removing it the AppImage works fine. Hope I didn't screw up my system... :)
