### ISSUE TITLE
2.10.32 can not start in Mageia 8.

### ISSUE THREAD

**Issue by z0cMWWKmGfudsDG** [ivan-hc/GIMP-appimage#4]
Run in console. Got below:
> /tmp/.mount_GNU_ImOuIjG6/AppRun:line 4: ::::::::::::::: Command not found
> ERROR: ld.so: object '/tmp/.mount_GNU_ImOuIjG6/usr/lib/x86_64-linux-gnu/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.
> ERROR: ld.so: object '/tmp/.mount_GNU_ImOuIjG6/usr/lib/x86_64-linux-gnu/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.
> ERROR: ld.so: object '/tmp/.mount_GNU_ImOuIjG6/usr/lib/x86_64-linux-gnu/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.
> ERROR: ld.so: object '/tmp/.mount_GNU_ImOuIjG6/usr/lib/x86_64-linux-gnu/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.
> ERROR: ld.so: object '/tmp/.mount_GNU_ImOuIjG6/usr/lib/x86_64-linux-gnu/' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.
> gimp-2.10: symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: g_ptr_array_copy

Then exited. Did not start successfully. In GNU/Linux distribution “Mageia 8”.GNU_Image_Manipulation_Program-2.10.32-x86_64.AppImage.

**Comment by ivan-hc** [comment]
what if you run:

     LD_DEBUG=libs ./GNU_Image_Manipulation_Program-2.10.32-x86_64.AppImage

? This should give you a more detailed output about the missing libraries (maybe on the host)

**Comment by z0cMWWKmGfudsDG** [comment]
[result.zip](https://github.com/ivan-hc/GIMP-appimage/files/9978275/result.zip)

**Comment by ivan-hc** [comment]
I have a doubt, is /lib64 a symlink to /lib or /usr/lib in Mageia or is it a different directory? I ask this because I had some problems with other AppImages from Debian to Arch Linux... Mageia is totally new for me.

Try the following steps:

     ./GNU_Image_Manipulation_Program-2.10.32-x86_64.AppImage --appimage-extract
now edit the AppRun, you should add `/lib64/:` to `LD_LIBRARY_PATH`, ie the line

     export LD_LIBRARY_PATH=/usr/lib/:/lib/:/usr/lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu/"${HERE}"/usr/lib/:"${HERE}"/usr/lib/gimp/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
should look like this

     export LD_LIBRARY_PATH=/lib64/:/usr/lib/:/lib/:/usr/lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu/"${HERE}"/usr/lib/:"${HERE}"/usr/lib/gimp/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
Now try to run the AppImage from the AppRun:

     cd squashfs-root
     ./AppRun
this is a first check, let me know if it works for you.

**Comment by z0cMWWKmGfudsDG** [comment]
It works.

In Mageia 8, there is a link “/lib/”to directory “/usr/lib/”, a link “/lib64/”to directory “/usr/lib64/”.

By the way, in the output selection. There are two selections of bmp, webp, dds, only one of them works. There is no selection “ora”.

You are friendly to GNU/Linux newbies.

**Comment by ivan-hc** [comment]
I've updated the scripts to include the path `/lib64/:` in `LD_LIBRARY_PATH`, just download the next release when it is ready, the GitHub action is running right now, it requires about 10-15 minutes to be completed.

https://github.com/ivan-hc/GIMP-appimage/releases/tag/continuous

If you say that this works for you, I think that its ok if I close the issue. 

Feel free to open this or another one incase of problems.

Bye
